In [21]:
import pandas as pd
import math

In [22]:
munis = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/Municipalities.csv')

In [23]:
energy_usage = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/EnergyUsage.csv')
joined = munis.merge(energy_usage.drop('Gemeentecode', axis=1), on='Gemeentenaam', how='left')
joined

,Gemeentecode,Gemeentenaam,Provinciecode,Provincienaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik
0,1680,AA EN HUNZE,22,DRENTHE,632890.0,1093470.0
1,358,AALSMEER,27,NOORD-HOLLAND,148310.0,319190.0
2,197,AALTEN,25,GELDERLAND,325310.0,690380.0
3,59,ACHTKARSPELEN,21,FRIESLAND,263420.0,482300.0
4,482,ALBLASSERDAM,28,ZUID-HOLLAND,255920.0,645420.0
...,...,...,...,...,...,...
350,879,ZUNDERT,30,NOORD-BRABANT,186160.0,404530.0
351,301,ZUTPHEN,25,GELDERLAND,370140.0,756230.0
352,1896,ZWARTEWATERLAND,23,OVERIJSSEL,361420.0,742320.0
353,642,ZWIJNDRECHT,28,ZUID-HOLLAND,656700.0,1468820.0
354,193,ZWOLLE,23,OVERIJSSEL,772210.0,1698240.0

In [24]:
total_weather = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/TotaalWeerStation.csv')
weerstation_per_gemeente = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/weerstation_per_gemeente.csv')

joined = joined.merge(weerstation_per_gemeente, on='Gemeentenaam', how='left')
joined = joined.merge(total_weather, on='WeerStation', how='left')
joined

,Gemeentecode,Gemeentenaam,Provinciecode,Provincienaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik,Unnamed: 0,distance,WeerStation,pctzon_gemiddeld,FG_gemiddeld
0,1680,AA EN HUNZE,22,DRENTHE,632890.0,1093470.0,9964.0,15.328115,EELDE,35.6,4.2
1,358,AALSMEER,27,NOORD-HOLLAND,148310.0,319190.0,3685.0,6.678455,SCHIPHOL,37.7,5.0
2,197,AALTEN,25,GELDERLAND,325310.0,690380.0,1858.0,17.757338,HUPSEL,36.3,3.4
3,59,ACHTKARSPELEN,21,FRIESLAND,263420.0,482300.0,611.0,26.136137,LEEUWARDEN,38.0,4.7
4,482,ALBLASSERDAM,28,ZUID-HOLLAND,255920.0,645420.0,5088.0,17.774848,ROTTERDAM,37.1,4.4
...,...,...,...,...,...,...,...,...,...,...,...
350,879,ZUNDERT,30,NOORD-BRABANT,186160.0,404530.0,8666.0,20.287061,GILZE-RIJEN,36.9,3.7
351,301,ZUTPHEN,25,GELDERLAND,370140.0,756230.0,2941.0,25.506100,DEELEN,35.0,3.8
352,1896,ZWARTEWATERLAND,23,OVERIJSSEL,361420.0,742320.0,11092.0,16.095447,MARKNESSE,38.2,4.2
353,642,ZWIJNDRECHT,28,ZUID-HOLLAND,656700.0,1468820.0,6726.0,19.319649,ROTTERDAM,37.1,4.4
354,193,ZWOLLE,23,OVERIJSSEL,772210.0,1698240.0,1810.0,25.449506,MARKNESSE,38.2,4.2

In [25]:
inhabitants = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/InhabitantsMunicipality.csv')
joined = joined.merge(inhabitants, on='Gemeentenaam', how='left')
joined

,Gemeentecode,Gemeentenaam,Provinciecode,Provincienaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik,Unnamed: 0,distance,WeerStation,pctzon_gemiddeld,FG_gemiddeld,Inwoneraantal,"Groot, middelgroot en klein"
0,1680,AA EN HUNZE,22,DRENTHE,632890.0,1093470.0,9964.0,15.328115,EELDE,35.6,4.2,NaN,NaN
1,358,AALSMEER,27,NOORD-HOLLAND,148310.0,319190.0,3685.0,6.678455,SCHIPHOL,37.7,5.0,31499.0,Klein
2,197,AALTEN,25,GELDERLAND,325310.0,690380.0,1858.0,17.757338,HUPSEL,36.3,3.4,NaN,NaN
3,59,ACHTKARSPELEN,21,FRIESLAND,263420.0,482300.0,611.0,26.136137,LEEUWARDEN,38.0,4.7,NaN,NaN
4,482,ALBLASSERDAM,28,ZUID-HOLLAND,255920.0,645420.0,5088.0,17.774848,ROTTERDAM,37.1,4.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,879,ZUNDERT,30,NOORD-BRABANT,186160.0,404530.0,8666.0,20.287061,GILZE-RIJEN,36.9,3.7,NaN,NaN
351,301,ZUTPHEN,25,GELDERLAND,370140.0,756230.0,2941.0,25.506100,DEELEN,35.0,3.8,47537.0,Klein
352,1896,ZWARTEWATERLAND,23,OVERIJSSEL,361420.0,742320.0,11092.0,16.095447,MARKNESSE,38.2,4.2,NaN,NaN
353,642,ZWIJNDRECHT,28,ZUID-HOLLAND,656700.0,1468820.0,6726.0,19.319649,ROTTERDAM,37.1,4.4,44586.0,Klein
354,193,ZWOLLE,23,OVERIJSSEL,772210.0,1698240.0,1810.0,25.449506,MARKNESSE,38.2,4.2,126116.0,Groot

In [26]:
postcodes = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/postcodeMunicipality.csv')
restricties = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/Restrictions.csv')

pr = postcodes.merge(restricties, on='Postcode', how='left')
pr_grouped = pr.groupby('Gemeentecode')['Kleur'].agg(list)

def remove_nans(mylist):
    cleaned_list = [x for x in mylist if str(x) != 'nan']

    if len(cleaned_list) == 0:
        return 'NO DATA'
    else:
        return max(set(cleaned_list), key = cleaned_list.count)

pr_grouped = pr_grouped.apply(remove_nans).reset_index()

pr_grouped
joined = joined.merge(pr_grouped, on='Gemeentecode', how='left')
joined

,Gemeentecode,Gemeentenaam,Provinciecode,Provincienaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik,Unnamed: 0,distance,WeerStation,pctzon_gemiddeld,FG_gemiddeld,Inwoneraantal,"Groot, middelgroot en klein",Kleur
0,1680,AA EN HUNZE,22,DRENTHE,632890.0,1093470.0,9964.0,15.328115,EELDE,35.6,4.2,NaN,NaN,GEEL
1,358,AALSMEER,27,NOORD-HOLLAND,148310.0,319190.0,3685.0,6.678455,SCHIPHOL,37.7,5.0,31499.0,Klein,NO DATA
2,197,AALTEN,25,GELDERLAND,325310.0,690380.0,1858.0,17.757338,HUPSEL,36.3,3.4,NaN,NaN,NO DATA
3,59,ACHTKARSPELEN,21,FRIESLAND,263420.0,482300.0,611.0,26.136137,LEEUWARDEN,38.0,4.7,NaN,NaN,NO DATA
4,482,ALBLASSERDAM,28,ZUID-HOLLAND,255920.0,645420.0,5088.0,17.774848,ROTTERDAM,37.1,4.4,NaN,NaN,NO DATA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,879,ZUNDERT,30,NOORD-BRABANT,186160.0,404530.0,8666.0,20.287061,GILZE-RIJEN,36.9,3.7,NaN,NaN,ORANJE
351,301,ZUTPHEN,25,GELDERLAND,370140.0,756230.0,2941.0,25.506100,DEELEN,35.0,3.8,47537.0,Klein,NO DATA
352,1896,ZWARTEWATERLAND,23,OVERIJSSEL,361420.0,742320.0,11092.0,16.095447,MARKNESSE,38.2,4.2,NaN,NaN,ROOD
353,642,ZWIJNDRECHT,28,ZUID-HOLLAND,656700.0,1468820.0,6726.0,19.319649,ROTTERDAM,37.1,4.4,44586.0,Klein,NO DATA
354,193,ZWOLLE,23,OVERIJSSEL,772210.0,1698240.0,1810.0,25.449506,MARKNESSE,38.2,4.2,126116.0,Groot,ROOD

In [27]:
sun = pd.read_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/2_preprocessed_data/sun.csv')
joined = joined.merge(sun, on='Gemeentenaam', how='left')
joined

,Gemeentecode,Gemeentenaam,Provinciecode,Provincienaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik,Unnamed: 0,distance,WeerStation,pctzon_gemiddeld,FG_gemiddeld,Inwoneraantal,"Groot, middelgroot en klein",Kleur,AantalInstallatiesBijWoningen,OpgesteldVermogenVanZonnepanelen
0,1680,AA EN HUNZE,22,DRENTHE,632890.0,1093470.0,9964.0,15.328115,EELDE,35.6,4.2,NaN,NaN,GEEL,7634.0,29820.0
1,358,AALSMEER,27,NOORD-HOLLAND,148310.0,319190.0,3685.0,6.678455,SCHIPHOL,37.7,5.0,31499.0,Klein,NO DATA,4866.0,17104.0
2,197,AALTEN,25,GELDERLAND,325310.0,690380.0,1858.0,17.757338,HUPSEL,36.3,3.4,NaN,NaN,NO DATA,5919.0,22730.0
3,59,ACHTKARSPELEN,21,FRIESLAND,263420.0,482300.0,611.0,26.136137,LEEUWARDEN,38.0,4.7,NaN,NaN,NO DATA,5151.0,22527.0
4,482,ALBLASSERDAM,28,ZUID-HOLLAND,255920.0,645420.0,5088.0,17.774848,ROTTERDAM,37.1,4.4,NaN,NaN,NO DATA,1759.0,5507.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,879,ZUNDERT,30,NOORD-BRABANT,186160.0,404530.0,8666.0,20.287061,GILZE-RIJEN,36.9,3.7,NaN,NaN,ORANJE,3513.0,15257.0
351,301,ZUTPHEN,25,GELDERLAND,370140.0,756230.0,2941.0,25.506100,DEELEN,35.0,3.8,47537.0,Klein,NO DATA,8097.0,23831.0
352,1896,ZWARTEWATERLAND,23,OVERIJSSEL,361420.0,742320.0,11092.0,16.095447,MARKNESSE,38.2,4.2,NaN,NaN,ROOD,3404.0,11751.0
353,642,ZWIJNDRECHT,28,ZUID-HOLLAND,656700.0,1468820.0,6726.0,19.319649,ROTTERDAM,37.1,4.4,44586.0,Klein,NO DATA,4229.0,13015.0
354,193,ZWOLLE,23,OVERIJSSEL,772210.0,1698240.0,1810.0,25.449506,MARKNESSE,38.2,4.2,126116.0,Groot,ROOD,28684.0,87308.0

In [28]:
joined.to_csv('C:/Users/20175878/Documents/GitHub/2AMD20-group19/3_map_data/map_dataset.csv', index=False)