In [57]:
import pandas as pd
import requests
import numpy as np
import io

CLEAN ENEXIS NET

In [10]:
url4 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/Clean_Enexis_net.csv"
DsRestrictions = pd.read_csv(url4, header = 0,encoding= 'unicode_escape', sep =",", usecols = ["Postal_Code", "Color","Station"])
DsRestrictions

    Postal_Code   Color                Station
0        4251AA  ORANJE              BIESBOSCH
1        4254AA  ORANJE              BIESBOSCH
2        4261AA    ROOD               WAALWIJK
3        4264AA    ROOD               WAALWIJK
4        4271AA  ORANJE        GEERTRUIDENBERG
..          ...     ...                    ...
958      9979AA    GEEL           Winsum Ranum
959      9981AA    GEEL  Eemshaven-Midden 20kV
960      9982AA    GEEL  Eemshaven-Midden 20kV
961      9989AA    GEEL           Winsum Ranum
962      9991AA    GEEL           Winsum Ranum

[963 rows x 3 columns]

GEMEENTEN ALFABETISCH

varname = Municipalities

In [41]:
urlMunicipalities = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/Gemeenten_alfabetisch_2019.xls"
dfMunicipalities = pd.read_excel(urlMunicipalities)

columnRenaming_municipalities = {}
columnsNecessary_municipalities = ['Gemeentecode','Gemeentenaam','Provinciecode','Provincienaam']

preProcessed_dfMunicipalities = dfMunicipalities[columnsNecessary_municipalities]
preProcessed_dfMunicipalities

     Gemeentecode     Gemeentenaam  Provinciecode  Provincienaam
0            1680      Aa en Hunze             22        Drenthe
1             358         Aalsmeer             27  Noord-Holland
2             197           Aalten             25     Gelderland
3              59    Achtkarspelen             21      Friesland
4             482     Alblasserdam             28   Zuid-Holland
..            ...              ...            ...            ...
350           879          Zundert             30  Noord-Brabant
351           301          Zutphen             25     Gelderland
352          1896  Zwartewaterland             23     Overijssel
353           642      Zwijndrecht             28   Zuid-Holland
354           193           Zwolle             23     Overijssel

[355 rows x 4 columns]

WINDENERGIE

varname = wind

In [40]:
urlWind = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/Windenergie_op_land__per_provincie_24052022_142754.csv"
dfWind = pd.read_csv(urlWind, header=0, encoding= "unicode_escape", sep =";" )

columnRenaming_wind = {"ï»¿\"Regio's\"":'Regio', 
                        "Perioden":"Periode"}
columnsNecessary_wind = ['Regio','Periode',
                            'Elektriciteitsproductie/Genormaliseerde productie (mln kWh)',
                        	'Elektriciteitsproductie/Productiefactor (%)',
                            'Elektrisch vermogen/Opgesteld vermogen einde jaar (megawatt)']
                            
preProcessed_dfWind = dfWind.rename(columnRenaming_wind, axis=1)
preProcessed_dfWind = preProcessed_dfWind[columnsNecessary_wind]
preProcessed_dfWind

,Regio,Periode,Elektriciteitsproductie/Genormaliseerde productie (mln kWh),Elektriciteitsproductie/Productiefactor (%),Elektrisch vermogen/Opgesteld vermogen einde jaar (megawatt)
0,Nederland,2019,7429.0,"25,9",3527
1,Nederland,2020,8962.0,"29,1",4159
2,Groningen (PV),2019,986.0,"26,7",450
3,Groningen (PV),2020,1083.0,"27,8",618
4,FryslÃ¢n (PV),2019,415.0,"25,8",197
5,FryslÃ¢n (PV),2020,451.0,"28,6",198
6,Drenthe (PV),2019,NaN,NaN,22
7,Drenthe (PV),2020,NaN,NaN,43
8,Overijssel (PV),2019,86.0,"23,1",61
9,Overijssel (PV),2020,142.0,27,66
10,Flevoland (PV),2019,2424.0,"24,8",1175
11,Flevoland (PV),2020,2531.0,"27,1",1169
12,Gelderland (PV),2019,152.0,"22,7",82
13,Gelderland (PV),2020,303.0,28,139
14,Utrecht (PV),2019,78.0,"27,8",34
15,Utrecht (PV),2020,88.0,"32,3",34
16,Noord-Holland (PV),2019,635.0,24,313
17,Noord-Holland (PV),2020,1270.0,31,641
18,Zuid-Holland (PV),2019,956.0,"27,7",437
19,Zuid-Holland (PV),2020,1122.0,"32,2",446
20,Zeeland (PV),2019,1189.0,"28,3",519
21,Zeeland (PV),2020,1327.0,"31,9",525
22,Noord-Brabant (PV),2019,442.0,"25,3",225
23,Noord-Brabant (PV),2020,541.0,28,259
24,Limburg (PV),2019,NaN,NaN,13
25,Limburg (PV),2020,NaN,NaN,21

ENERGIEVERBRUIK PARTICULIER

varname = energyUsage

<sup>--> vraag: willen we iets doen met woningkenmerken (e.g. rijtjeshuis)?<sup>

In [72]:
urlEnergyUsage = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/energieverbruik%20particuliere%20woniningen%20-%2084837NED_UntypedDataSet_21052022_135719.csv"
dfEnergyUsage = pd.read_csv(urlEnergyUsage, header=0, encoding= "unicode_escape", sep =";")

columnRenaming_energyUsage = {"Gemeentenaam_1":'Gemeentenaam', 
                        "GemiddeldAardgasverbruik_4":"GemiddeldAardgasverbruik",
                        "GemiddeldElektriciteitsverbruik_5":"GemiddeldElektriciteitsverbruik"}
columnsNecessary_energyUsage = ["Gemeentenaam", "GemiddeldAardgasverbruik","GemiddeldElektriciteitsverbruik"]

preProcessed_dfEnergyUsage = dfEnergyUsage.rename(columnRenaming_energyUsage, axis=1)
preProcessed_dfEnergyUsage = preProcessed_dfEnergyUsage[columnsNecessary_energyUsage]

preProcessed_dfEnergyUsage["GemiddeldAardgasverbruik"] = pd.to_numeric(preProcessed_dfEnergyUsage["GemiddeldAardgasverbruik"], errors="coerce")
preProcessed_dfEnergyUsage["GemiddeldElektriciteitsverbruik"] = pd.to_numeric(preProcessed_dfEnergyUsage["GemiddeldElektriciteitsverbruik"], errors="coerce")

grouped_preProcessed_dfEnergyUsage = preProcessed_dfEnergyUsage.groupby(["Gemeentenaam"])[["GemiddeldAardgasverbruik","GemiddeldElektriciteitsverbruik"]].sum().reset_index()
grouped_preProcessed_dfEnergyUsage

,Gemeentenaam,GemiddeldAardgasverbruik,GemiddeldElektriciteitsverbruik
0,'s-Gravenhage,1344290.0,3002430.0
1,'s-Hertogenbosch,985580.0,2318090.0
2,Aa en Hunze,632890.0,1093470.0
3,Aalsmeer,148310.0,319190.0
4,Aalten,325310.0,690380.0
...,...,...,...
351,Zundert,186160.0,404530.0
352,Zutphen,370140.0,756230.0
353,Zwartewaterland,361420.0,742320.0
354,Zwijndrecht,656700.0,1468820.0
355,Zwolle,772210.0,1698240.0

INWONERS PER GEMEENTE

varname = InhabitantsMunicipality

In [80]:
urlInhabitantsMunicipality = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/inwoners%20per%20gemeente.csv"
dfInhabitantsMunicipality = pd.read_csv(urlInhabitantsMunicipality, header=0, encoding= "unicode_escape", sep =";" )

columnRenaming_inhabitantsMunicipality = {'Gemeente':'Gemeentenaam'}
columnsNecessary_inhabitantsMunicipality = ["Gemeentenaam", "Inwoneraantal" ,"Groot, middelgroot en klein"]
                            
preProcessed_inhabitantsMunicipality = dfInhabitantsMunicipality.rename(columnRenaming_inhabitantsMunicipality, axis=1)
preProcessed_inhabitantsMunicipality = preProcessed_inhabitantsMunicipality[columnsNecessary_inhabitantsMunicipality]

preProcessed_inhabitantsMunicipality["Inwoneraantal"] = pd.to_numeric(preProcessed_inhabitantsMunicipality["Inwoneraantal"], errors="coerce")
preProcessed_inhabitantsMunicipality = preProcessed_inhabitantsMunicipality[preProcessed_inhabitantsMunicipality["Inwoneraantal"] > 30000]
preProcessed_inhabitantsMunicipality['Gemeentenaam'] = preProcessed_inhabitantsMunicipality['Gemeentenaam'].map(lambda x: x.strip("?"))

preProcessed_inhabitantsMunicipality

            Gemeentenaam  Inwoneraantal Groot, middelgroot en klein
1               Aalsmeer          31499                       Klein
6                Alkmaar         108470                       Groot
7                 Almelo          72629                 Middelgroot
8                 Almere         203990                       Groot
9    Alphen aan den Rijn         109682                       Groot
..                   ...            ...                         ...
347           Zoetermeer         124695                       Groot
349             Zuidplas          41882                       Klein
351              Zutphen          47537                       Klein
353          Zwijndrecht          44586                       Klein
354               Zwolle         126116                       Groot

[177 rows x 3 columns]

PC6-GWB2020

In [81]:


#postcodes linked to municipalitiecodes. 

url5 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/pc6-gwb2020.csv"
DsPostcodesPre = pd.read_csv(url5, header =0 , sep = ";", usecols =[ "PC6", "Gemeente2020"])
#DsPostcodesPre.rename(columns = {"PC6": "Postal_Code"})
DsPostcodesPre.columns = ["Postal_Code","Gemeente2020"] 
print(DsPostcodesPre.columns) 

DsPostcodes.head()

#NO
#municipalitycodes linked to municipalities
#url6 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/client_data/GEMEENTECODES1.csv"
#download1 = requests.get(url6).content
#DsMunicodes = pd.read_csv(io.StringIO(download1.decode("utf-16-le")), encoding= "utf-16-le", header=0, sep=';',skipinitialspace = True)
#DsMunicodes = pd.read_csv(io.StringIO(download1.decode("utf")) header =0 , sep = ";" )
#encoding = "ISO-8859-1"
#print(DsMunicodes.columns)

#DsMunicodes.decode('utf-16-le').split()
#DsMunicodes.head()

#DsPostcodes.head()

Index(['Postal_Code', 'Gemeente2020'], dtype='object')

NameError: name 'DsPostcodes' is not defined

ZONNESTROOM VERMOGEN

In [ ]:
url = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/zonnestroom%20vermogen%202019%20-%2085010NED_UntypedDataSet_21052022_134211.csv"
download = requests.get(url).content
DsSun = pd.read_csv(io.StringIO(download.decode("utf")), header=0, sep=';',usecols = ["Gemeentenaam_1", "AantalInstallatiesBijWoningen_5" , "OpgesteldVermogenVanZonnepanelen_6"],skipinitialspace = True)
#Aantal zonnepaneel installaties per gemeente en het opgesteld vermogen
print(DsSunMuni.columns)
DsSunMuni = DsSun.groupby(["Gemeentenaam_1"])["AantalInstallatiesBijWoningen_5", "OpgesteldVermogenVanZonnepanelen_6"].sum()
print(DsSunMuni.columns)
DsSunMuni.head()

KAN MOGELIJK WEG?

In [ ]:
#Matching postalcodes to Municipality code
#colums = ,Postal_Code,Color,Station
print(DsRestrictions.shape, DsRestrictions.columns,DsPostcodesPre.shape, DsPostcodesPre.columns )
#restrictions are only available for 963 municipalities thus drastically lowering amount of municiaplities

#merge will add NA to values that do not exist on left or right Filter these out later. 
#Merge on postalcode add municipality right join to 
#combine colors and stations to municipality code(gemeente2020)
DsMunicipality = pd.merge(DsRestrictions, DsPostcodesPre, on = "Postal_Code")
#groupby gemeentecode 
DsMunicipality = DsMunicipality.groupby(["Gemeente2020"])["Station", "Color"].first()

#Gemeentecode - Station - Colour
DsMunicipality.head()

#matching municipalities to provinces