In [270]:
import pandas as pd
import requests
import numpy
import io

In [272]:
url = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/zonnestroom%20vermogen%202019%20-%2085010NED_UntypedDataSet_21052022_134211.csv"
download = requests.get(url).content
DsSun = pd.read_csv(io.StringIO(download.decode("utf")), header=0, sep=';',usecols = ["Gemeentenaam_1", "AantalInstallatiesBijWoningen_5" , "OpgesteldVermogenVanZonnepanelen_6"],skipinitialspace = True)
#Aantal zonnepaneel installaties per gemeente en het opgesteld vermogen
print(DsSunMuni.columns)
DsSunMuni = DsSun.groupby(["Gemeentenaam_1"])["AantalInstallatiesBijWoningen_5", "OpgesteldVermogenVanZonnepanelen_6"].sum()
print(DsSunMuni.columns)
DsSunMuni.head()

Index(['AantalInstallatiesBijWoningen_5', 'OpgesteldVermogenVanZonnepanelen_6'], dtype='object')
Index(['AantalInstallatiesBijWoningen_5', 'OpgesteldVermogenVanZonnepanelen_6'], dtype='object')

C:\Users\Rodin\AppData\Local\Temp/ipykernel_12512/1539153231.py:6: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  DsSunMuni = DsSun.groupby(["Gemeentenaam_1"])["AantalInstallatiesBijWoningen_5", "OpgesteldVermogenVanZonnepanelen_6"].sum()

,AantalInstallatiesBijWoningen_5,OpgesteldVermogenVanZonnepanelen_6
Gemeentenaam_1,,
,0.0,0.0
's-Gravenhage,29805.0,76786.0
's-Hertogenbosch,18673.0,66087.0
Aa en Hunze,7634.0,29820.0
Aalsmeer,4866.0,17104.0

In [285]:
#Later after merging remove columns where muncipalities are smaller then 30.000
url1 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/inwoners%20per%20gemeente.csv"
DsHabitants = pd.read_csv(url1, header = 0,encoding= 'unicode_escape', sep =";" , usecols = ["Gemeente", "Inwoneraantal" ,"Groot, middelgroot en klein"])
DsHabitants["Inwoneraantal"] = pd.to_numeric(DsHabitants["Inwoneraantal"], errors="coerce")
DsHabitants["Gemeente"] = DsHabitants["Gemeente"].map(lambda x: x.strip("?"))

#filter out very small municipalities 
#DsHabitants.drop(DsHabitants.loc[DsHabitants["Groot, middelgroot en klein"].index != "Klein"], axis=1)
#DsHabitants = DsHabitants[DsHabitants["Inwoneraantal" != "Klein"]]
DsHabitants = DsHabitants[DsHabitants["Inwoneraantal"] > 30000]

#DsHabitants.drop(DsHabitants[DsHabitants["Inwoneraantal"] >= 30.000].index, inplace = True)
#DsHabitants = DsHabitants.loc[DsHabitants.Inwoneraantal >= 30.000]
#DsHabitants[DsHabitants.apply(lambda x: True if (x.Inwoneraantal) >= 30.000 else False,axis=1)]

#Filter out small municipalities

DsHabitants.head()

              Gemeente  Inwoneraantal Groot, middelgroot en klein
1             Aalsmeer          31499                       Klein
6              Alkmaar         108470                       Groot
7               Almelo          72629                 Middelgroot
8               Almere         203990                       Groot
9  Alphen aan den Rijn         109682                       Groot

In [274]:
#energy use per municipality both for gas and electrity
url2 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/energieverbruik%20particuliere%20woniningen%20-%2084837NED_UntypedDataSet_21052022_135719.csv"
DsEnergy = pd.read_csv(url2, header=0, encoding="unicode_escape", sep=";", usecols = ["Gemeentenaam_1", "GemiddeldAardgasverbruik_4","GemiddeldElektriciteitsverbruik_5", "Woningkenmerken" ])
#groupby municipality and count total number of gas and electicity


#and count total number of gas and electicity
DsEnergy["GemiddeldAardgasverbruik_4"] = pd.to_numeric(DsEnergy["GemiddeldAardgasverbruik_4"], errors="coerce")
DsEnergy["GemiddeldElektriciteitsverbruik_5"] = pd.to_numeric(DsEnergy["GemiddeldElektriciteitsverbruik_5"], errors="coerce")
DsEnergyMuni = DsEnergy.groupby(["Gemeentenaam_1"])["GemiddeldAardgasverbruik_4","GemiddeldElektriciteitsverbruik_5"].sum()
#DsEnergyMuni1 = DsEnergy.groupby(["Gemeentenaam_1"])["GemiddeldElektriciteitsverbruik_5"].sum()


DsEnergyMuni.head()


#DsEnergy.head(n =20)

C:\Users\Rodin\AppData\Local\Temp/ipykernel_12512/532775517.py:10: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  DsEnergyMuni = DsEnergy.groupby(["Gemeentenaam_1"])["GemiddeldAardgasverbruik_4","GemiddeldElektriciteitsverbruik_5"].sum()

,GemiddeldAardgasverbruik_4,GemiddeldElektriciteitsverbruik_5
Gemeentenaam_1,,
's-Gravenhage,1344290.0,3002430.0
's-Hertogenbosch,985580.0,2318090.0
Aa en Hunze,632890.0,1093470.0
Aalsmeer,148310.0,319190.0
Aalten,325310.0,690380.0

In [203]:
url7 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/energieverbruik%20particuliere%20woniningen%20-%2084837NED_UntypedDataSet_21052022_135719.csv"
DsMuniCharacteristics = pd.read_csv(url7, header=0, encoding="unicode_escape", sep=";", usecols = ["Gemeentenaam_1", "Woningkenmerken"])

#create a list for each municipality with the characteristics?


DsMuniCharacteristics.head()

  Woningkenmerken                            Gemeentenaam_1
0         T001100  Nederland
1         ZW25810  Nederland
2         ZW25805  Nederland
3         ZW25806  Nederland
4         ZW10300  Nederland

In [304]:
#Columns willen niet meewerken
#Productie factor en genormaliseerde productie per provincie

#filter out for 2019 -> perioden
url3 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/Windenergie_op_land__per_provincie_24052022_142754.csv"
DsWind = pd.read_csv(url3, header=0, encoding= "unicode_escape", sep =";" )
# DsWind.columns = DsWind.columns.str.replace("/", " ")
# DsWind.columns = DsWind.columns.str.replace("'", " ")
# DsWind.columns = DsWind.columns.str.replace("(", " ")
# DsWind.columns = DsWind.columns.str.replace(")", " ")
# DsWind.columns = DsWind.columns.str.replace("mln kWh", " ")
# DsWind.columns = DsWind.columns.str.replace("%", " ")
# DsWind.columns = DsWind.columns.str.replace(" ", "")
#keep_col = ["Regios", "Perioden", "Elektriciteitsproductie Genormaliseerde productie", "Elektriciteitsproductie Productiefactor"]

#DsWind1 = DsWind[]
DsWindNew = DsWind[["ï»¿\"Regio's\"", "Perioden", "Elektriciteitsproductie/Genormaliseerde productie (mln kWh)", "Elektriciteitsproductie/Productiefactor (%)", "Elektrisch vermogen/Opgesteld vermogen einde jaar (megawatt)"]]

DsWindNew = DsWindNew.rename({"ï»¿\"Regio's\"":"Regio"}, axis=1)
#DsWind.drop("Windmolens/In gebruik genomen windmolens (aantal)", inplace=True, axis=1)
#DsWind.head(n=10)
# DAtaframe and drop columns
#"Regio's"
#"Elektriciteitsproductie/Genormaliseerde productie (mln kWh)",
#, "Elektriciteitsproductie/Productiefactor (%)
DsWindNew

,Regio,Perioden,Elektriciteitsproductie/Genormaliseerde productie (mln kWh),Elektriciteitsproductie/Productiefactor (%),Elektrisch vermogen/Opgesteld vermogen einde jaar (megawatt)
0,Nederland,2019,7429.0,"25,9",3527
1,Nederland,2020,8962.0,"29,1",4159
2,Groningen (PV),2019,986.0,"26,7",450
3,Groningen (PV),2020,1083.0,"27,8",618
4,FryslÃ¢n (PV),2019,415.0,"25,8",197
5,FryslÃ¢n (PV),2020,451.0,"28,6",198
6,Drenthe (PV),2019,NaN,NaN,22
7,Drenthe (PV),2020,NaN,NaN,43
8,Overijssel (PV),2019,86.0,"23,1",61
9,Overijssel (PV),2020,142.0,27,66
10,Flevoland (PV),2019,2424.0,"24,8",1175
11,Flevoland (PV),2020,2531.0,"27,1",1169
12,Gelderland (PV),2019,152.0,"22,7",82
13,Gelderland (PV),2020,303.0,28,139
14,Utrecht (PV),2019,78.0,"27,8",34
15,Utrecht (PV),2020,88.0,"32,3",34
16,Noord-Holland (PV),2019,635.0,24,313
17,Noord-Holland (PV),2020,1270.0,31,641
18,Zuid-Holland (PV),2019,956.0,"27,7",437
19,Zuid-Holland (PV),2020,1122.0,"32,2",446
20,Zeeland (PV),2019,1189.0,"28,3",519
21,Zeeland (PV),2020,1327.0,"31,9",525
22,Noord-Brabant (PV),2019,442.0,"25,3",225
23,Noord-Brabant (PV),2020,541.0,28,259
24,Limburg (PV),2019,NaN,NaN,13
25,Limburg (PV),2020,NaN,NaN,21

In [277]:
#Energy net restrictions on postal codes given in color codes

#TODO: merge this with the next postcode to municipality DF next cell. 

#colums = ,Postal_Code,Color,Station
url4 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/Clean_Enexis_net.csv"
DsRestrictions = pd.read_csv(url4, header = 0,encoding= 'unicode_escape', sep =",", usecols = ["Postal_Code", "Color","Station"])
#DsRestrictions["Gemeente"] = DsRestrictions["Gemeente"].map(lambda x: x.strip("?"))

DsRestrictions.head()

  Postal_Code   Color          Station
0      4251AA  ORANJE        BIESBOSCH
1      4254AA  ORANJE        BIESBOSCH
2      4261AA    ROOD         WAALWIJK
3      4264AA    ROOD         WAALWIJK
4      4271AA  ORANJE  GEERTRUIDENBERG

In [305]:
#postcodes linked to municipalitiecodes. 

url5 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/1_source_data/pc6-gwb2020.csv"
DsPostcodesPre = pd.read_csv(url5, header =0 , sep = ";", usecols =[ "PC6", "Gemeente2020"])
#DsPostcodesPre.rename(columns = {"PC6": "Postal_Code"})
DsPostcodesPre.columns = ["Postal_Code","Gemeente2020"] 
print(DsPostcodesPre.columns) 

DsPostcodes.head()

#NO
#municipalitycodes linked to municipalities
#url6 = "https://raw.githubusercontent.com/lucasnijder/2AMD20-group19/main/client_data/GEMEENTECODES1.csv"
#download1 = requests.get(url6).content
#DsMunicodes = pd.read_csv(io.StringIO(download1.decode("utf-16-le")), encoding= "utf-16-le", header=0, sep=';',skipinitialspace = True)
#DsMunicodes = pd.read_csv(io.StringIO(download1.decode("utf")) header =0 , sep = ";" )
#encoding = "ISO-8859-1"
#print(DsMunicodes.columns)

#DsMunicodes.decode('utf-16-le').split()
#DsMunicodes.head()

#DsPostcodes.head()

Index(['Postal_Code', 'Gemeente2020'], dtype='object')

      PC6  Gemeente2020
0  1011AB           363
1  1011AC           363
2  1011AD           363
3  1011AE           363
4  1011AG           363

In [255]:
#Matching postalcodes to Municipality code
#colums = ,Postal_Code,Color,Station
print(DsRestrictions.shape, DsRestrictions.columns,DsPostcodesPre.shape, DsPostcodesPre.columns )
#restrictions are only available for 963 municipalities thus drastically lowering amount of municiaplities

#merge will add NA to values that do not exist on left or right Filter these out later. 
#Merge on postalcode add municipality right join to 
#combine colors and stations to municipality code(gemeente2020)
DsMunicipality = pd.merge(DsRestrictions, DsPostcodesPre, on = "Postal_Code")
#groupby gemeentecode 
DsMunicipality = DsMunicipality.groupby(["Gemeente2020"])["Station", "Color"].first()

#Gemeentecode - Station - Colour
DsMunicipality.head()

#matching municipalities to provinces

(963, 3) Index(['Postal_Code', 'Color', 'Station'], dtype='object') (489653, 2) Index(['Postal_Code', 'Gemeente2020'], dtype='object')

C:\Users\Rodin\AppData\Local\Temp/ipykernel_12512/3286433637.py:11: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  DsMunicipality = DsMunicipality.groupby(["Gemeente2020"])["Station", "Color"].first()

                            Station Color
Gemeente2020
3                      Weiwerd 20kV  ROOD
10            Eemshaven-Midden 20kV  GEEL
14                       Kropswolde  ROOD
24                     Weiwerd 20kV  ROOD
37                      STADSKANAAL  ROOD

(355, 3) Index(['Gemeente', 'Inwoneraantal', 'Groot, middelgroot en klein'], dtype='object') (358, 2) Index(['AantalInstallatiesBijWoningen_5', 'OpgesteldVermogenVanZonnepanelen_6'], dtype='object') Index(['GemiddeldAardgasverbruik_4', 'GemiddeldElektriciteitsverbruik_5'], dtype='object')